services:

  scratch-web:
    image: nginx:alpine
    container_name: scratch_web
    restart: always

    ports:
      - "80:80"

    volumes:
      - ./html:/usr/share/nginx/html:ro,Z


  scratch-api:
    build:
      context: ./api

    container_name: scratch_api
    restart: always

    working_dir: /app

    ports:
      - "3000:3000"

    volumes:
      - ./data/students.json:/app/students.json:Z
      - ./data/teachers.json:/app/teachers.json:Z
      - ./data/settings.json:/app/settings.json:Z
      - ./data/uploads:/app/uploads:Z
      - ./data/deleted-classes:/app/deleted-classes:Z
      - ./data/restored-classes:/app/restored-classes:Z
