
services:
  # 1. 儲存作品與前端的 Nginx
  scratch-web:
    image: nginx:alpine
    container_name: scratch_web
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  # 2. Node.js 作品 API 伺服器
  scratch-api:
    image: node:18-alpine
    container_name: scratch_api
    restart: always
    working_dir: /app
    environment:
      GOOGLE_CLIENT_ID: "523864494781-to69fphr1ae35acecktlo4053eirco1q.apps.googleusercontent.com"
    volumes:
      - ./api:/app
    command: node server.js
    ports:
      - "3000:3000"
